# Generated by Django 4.2 on 2023-04-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_shareditem_shared_by_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedItem',
        ),
    ]
