# Generated by Django 4.2 on 2023-04-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_delete_shareditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_delete_shareditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_to_emails', models.TextField()),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.note')),
                ('shared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task')),
            ],
        ),
    ]
