# Generated by Django 4.2 on 2023-04-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedItem',
        ),
    ]
